export default [
  {
    id: 1,
    category: "app",
    title: "SSR Widget - Micro Frontend",
    tech: "Next.js 14, TypeScript, Micro Frontend, SSR, Kafka, Microservices",
    description: "My biggest achievement - A micro-frontend sports aggregation platform with live scores, stats, and updates across 8+ major sports. Embeddable widget architecture.",
    link: "https://ssr-widget-7jj6.vercel.app/",
    thumbnail: "https://ssr-widget-7jj6.vercel.app/favicon.ico",
    featured: true,
  },
  {
    id: 2,
    category: "app",
    title: "Racing And Sports UK",
    tech: "Next.js 14, TypeScript, React Query, TailwindCSS, Kafka",
    description: "Real-time sports platform with SSR, JSON-LD schemas, dynamic sitemaps serving 100K+ daily users",
    link: "https://racingandsports.co.uk/",
    thumbnail: "https://racingandsports.co.uk/assets/svg/rasBrandLogo.svg",
  },
  {
    id: 3,
    category: "app",
    title: "Football First",
    tech: "React.js, Next.js, TailwindCSS, SSR",
    description: "Multi-sport live platform with mobile-first design and caching strategies",
    link: "https://www.footballfirst.com/",
    thumbnail: "https://footballfirst.com/storage/images/logo/header_light_logo_1745408002_a945c709-47b7-4ed3-8cd2-cdef7275b99c.svg",
  },
  {
    id: 4,
    category: "app",
    title: "Betway Scores",
    tech: "React.js, Next.js, Redux Toolkit, WebSockets",
    description: "Dynamic live score app with real-time API integration, 90+ Lighthouse scores",
    link: "https://www.betwayscores.com/",
    thumbnail: "https://www.betwayscores.com/_next/image?url=%2Fimages%2FBetwayLogoNew.png&w=384&q=75",
  },
  {
    id: 5,
    category: "app",
    title: "Score Mania",
    tech: "React.js, Custom Hooks, TailwindCSS, SSR",
    description: "Multi-sport live platform with comprehensive sports coverage",
    link: "https://www.scoremania.com/",
    thumbnail: "https://scoremania.com/storage/images/logo/header_dark_logo_1751379405_6e72ff02-9663-421f-b24d-b5c63955202d.png",
  },
  {
    id: 6,
    category: "app",
    title: "Planet Baseball",
    tech: "Next.js, TypeScript, React Query, Microservices",
    description: "Dedicated baseball platform with live scores and analytics",
    link: "https://www.planetbaseball.com/",
    thumbnail: "https://planetbaseball.com/storage/images/logo/header_dark_logo_1738320696_736614e1-7345-4e38-9131-211c7adaa677.svg",
  },
  {
    id: 7,
    category: "app",
    title: "Hollywood Bets Live Score",
    tech: "React.js, Next.js, Redux Toolkit, WebSockets",
    description: "Real-time live score platform with seamless data integration for South African market",
    link: "https://www.hollywoodbets.net/",
    thumbnail: "https://www.hollywoodbets.net/images/hollywood-logo.svg",
  },
];
