export default {
  meta_title: "Muhammad Gohar | Frontend Engineer | React Developer | AI Prompt Engineer",
  meta_description:
    "Results-driven Frontend Engineer and React Developer with 2+ years of experience building scalable, high-performance, SEO-optimized web applications. Expert in React.js, Next.js 14, TypeScript, and JavaScript (ES6+). AI-Powered Developer leveraging Claude AI and Claude Code CLI for 5x productivity improvement. Proficient in SSR, SSG, ISR, Apache Kafka, and real-time applications serving 100K+ daily users. Based in Lahore, Pakistan.",
  meta_keywords:
    "Muhammad Gohar, Frontend Engineer, React Developer, AI Prompt Engineer, Claude AI Developer, Next.js 14 Expert, TypeScript Developer, JavaScript ES6+, Web Development, React.js, SSR, SSG, ISR, Server-Side Rendering, Static Site Generation, Apache Kafka, WebSockets, Real-Time Applications, Redux Toolkit, React Query, TailwindCSS, Shadcn UI, Technical SEO, JSON-LD Schema, XML Sitemaps, Core Web Vitals, AI-Assisted Development, Claude Code CLI, MCP Protocol, Prompt Engineering, LLM Integration, Full-Stack Development, Node.js, NestJS, REST APIs, GraphQL, MongoDB, PostgreSQL, High-Performance Applications, Scalable Web Solutions, Lahore Developer, Pakistan Software Engineer, Live Sports Platforms, Racing and Sports UK, Betway Scores, Hollywood Bets",
  key_values:
    "Top Frontend Engineer in Pakistan, React.js and Next.js 14 Expert, AI-Powered Developer, Claude AI Power User, 5x Development Productivity, TypeScript and JavaScript Expert, Real-Time Web Applications, Live Sports Platforms Developer, 100K+ Daily Users, High-Performance Web Apps, SEO-Optimized Applications, Server-Side Rendering Expert, Apache Kafka Integration, WebSocket Applications, State Management Expert, Redux Toolkit, React Query TanStack, TailwindCSS Developer, Modern UI/UX, Responsive Web Design, Mobile-First Development, AI Prompt Engineering, Claude Code CLI, MCP Tools Integration, LLM Application Developer, Technical Documentation Expert, Markdown Documentation, Best Frontend Portfolio 2024, FAST-NUCES Graduate, Sixlogics Engineer, Enterprise Web Applications, Microservices Architecture, Event-Driven Architecture, Code Review Expert, Junior Developer Mentor, Agile Development, Clean Code Practices",
  image: "/assets/img/gohar.jpeg",
};
