export default {
  meta_title: "Muhammad Gohar Butt | Software Engineer",
  meta_description:
    "Results-driven Software Engineer with 3+ years of experience specializing in React.js, Next.js, NestJS, and API integrations. Proven expertise in developing scalable, high-performance web applications, optimizing backend workflows, and delivering real-time platforms. Skilled in JavaScript, TypeScript, MySQL, AWS, and CI/CD pipelines, with strong problem-solving abilities. Passionate about technology, cloud computing, SEO optimization, and agile development. Based in Riyadh, KSA, actively seeking innovative opportunities in software engineering.",
  meta_keywords:
    "Muhammad Gohar Butt, Software Engineer, Full-Stack Developer, Frontend Developer, Backend Developer, React.js Developer, Next.js Developer, Node.js Engineer, NestJS Expert, API Integration, Web Development, SaaS Development, Cloud Computing, AWS, DevOps, Scalable Web Solutions, SEO Optimization, JavaScript, TypeScript, MySQL, PostgreSQL, MongoDB, UI/UX, Google Rankings, Page Speed Optimization, Google Lighthouse, Web Performance, Agile Development, Best Software Engineer in Riyadh, Riyadh Tech Jobs, KSA Software Engineers, Middle East Developers, Web Security, Middleware Development, REST APIs, GraphQL, Google Schema Markup, Website Indexing, Technical SEO, Digital Transformation, Web 3.0, AI-Powered Web Apps, Progressive Web Apps (PWA), Software Architecture, IT Consultant, Best React Developer, Best Next.js Developer, Fastest Websites, Google Page Ranking, High-Performance Applications",
  key_values:
    "Top Software Engineer in Riyadh, KSA Web Developer, React.js and Next.js Expert, JavaScript and TypeScript Engineer, Cloud-Based Applications, Web App Development, API-First Development, Best Tech Portfolio 2024, High-Performance Websites, SEO-Optimized Web Applications, SaaS Engineer, Future of Web Development, Cutting-Edge Tech Solutions, AI and Web Development, Software as a Service, Serverless Applications, DevOps Best Practices, Scalable and Secure Web Solutions, Tech Thought Leadership, Leading Software Innovators, API Automation, Google Lighthouse Optimization, Website Performance Enhancements, E-Commerce Solutions, Best Web Developer in Saudi Arabia, Top Web Security Practices, Frontend Optimization, Digital Growth Strategies, Growth-Driven Development, Google Search Engine Best Practices, Expert in Web Frameworks, AI-Powered SEO, Mobile-First Development, UX/UI Optimization, Expert Software Portfolio, Best Tech Resume 2024",
  image: "/assets/img/gohar.jpeg",
};
